In [83]:
from pathlib import Path
import numpy as np
import pandas as pd
import toolz

In [136]:
raw = Path("input.txt").read_text().split("\n")

In [137]:
hand2 = {
    "X" : 1,
    "Y" : 2,
    "Z" : 3
}

hand1 = {
    "A" : "X",  # Rock
    "B" : "Y",  # Paper
    "C" : "Z"   # Scissor
}

rules = {
    "XX" : "D",
    "YY" : "D",
    "ZZ" : "D",
    "XY" : "W",
    "XZ" : "L",
    "YX" : "L",
    "YZ" : "W",
    "ZX" : "W",
    "ZY" : "L"
}

game = {
    "W" : 6,
    "D" : 3,
    "L" : 0
}

result = {
    "X" : "L",
    "Y" : "D",
    "Z" : "W"
}

In [138]:
df = pd.DataFrame(list(map(lambda x: x.split(" "), raw)), columns=["Code", "Elf2"])

In [139]:
df["Elf1"] = df["Code"].map(hand1)
df["Game"] = df["Elf1"] + df["Elf2"]
df["Result"] = df["Game"].map(rules)
df["Score"] = df["Result"].map(game)
df["Extra"] = df["Elf2"].map(hand2)
df["Total"] = df["Score"] + df["Extra"]

In [140]:
df.Total.sum()

15337

In [142]:
df["Predict"] = df["Elf2"].map(result)

In [143]:
def predict(outcome, hand):
    options = toolz.valfilter(lambda x: x == outcome, rules)
    return toolz.first(toolz.keyfilter(lambda x: x.startswith(hand), options).keys())[1]

In [144]:
df["Outcome"] = df[["Predict", "Elf1"]].apply(lambda x: predict(x.Predict, x.Elf1), axis=1)

In [145]:
df["Game2"] = df["Elf1"] + df["Outcome"]
df["Result2"] = df["Game2"].map(rules)
df["Score2"] = df["Result2"].map(game)
df["Extra2"] = df["Outcome"].map(hand2)
df["Total2"] = df["Score2"] + df["Extra2"]

In [146]:
df

,Code,Elf2,Elf1,Game,Result,Score,Extra,Total,Predict,Outcome,Game2,Result2,Score2,Extra2,Total2
0,B,X,Y,YX,L,0,1,1,L,X,YX,L,0,1,1
1,B,Z,Y,YZ,W,6,3,9,W,Z,YZ,W,6,3,9
2,B,Z,Y,YZ,W,6,3,9,W,Z,YZ,W,6,3,9
3,A,Y,X,XY,W,6,2,8,D,X,XX,D,3,1,4
4,B,X,Y,YX,L,0,1,1,L,X,YX,L,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,B,Z,Y,YZ,W,6,3,9,W,Z,YZ,W,6,3,9
2496,B,Z,Y,YZ,W,6,3,9,W,Z,YZ,W,6,3,9
2497,A,Y,X,XY,W,6,2,8,D,X,XX,D,3,1,4
2498,A,Y,X,XY,W,6,2,8,D,X,XX,D,3,1,4
2499,A,Y,X,XY,W,6,2,8,D,X,XX,D,3,1,4

In [147]:
df.Total2.sum()

11696